### ISSUE TITLE
Check out how volume keys are working. 

### ISSUE THREAD

**Issue by Viewfinder-issues** [Viewfinder-issues/Viewfinder#42]
From: 48569B5A-8983-4C10-99D7-2CB68F7815C7
Are we using AVAudioSession.sessionVolumeKeyPath.

**Comment by adam-fowler** [comment]
Check https://github.com/jpsim/JPSVolumeButtonHandler

**Comment by adam-fowler** [comment]
This issue was moved to adam-fowler/Viewfinder#88
