### ISSUE TITLE
Check under/over exposed warning when changing ev comp 

### ISSUE THREAD

**Issue by adam-fowler** [Viewfinder-issues/Viewfinder#82]
_From @adam-fowler on April 2, 2017 9:43_

_From @Viewfinder-issues on April 1, 2017 20:34_

From: 48569B5A-8983-4C10-99D7-2CB68F7815C7

_Copied from original issue: Viewfinder-issues/Viewfinder#61_

_Copied from original issue: adam-fowler/Viewfinder#105_

**Comment by Viewfinder-issues** [comment]
closing as duplicate of https://github.com/Viewfinder-issues/Viewfinder/issues/84
